backend:
  name: github
  repo: SurakanK/asuras-web-admin
  branch: main
  commit_messages:
  create: "Create {{collection}} “{{slug}}”"
  update: "Update {{collection}} “{{slug}}”"
  delete: "Delete {{collection}} “{{slug}}”"
  uploadMedia: "[skip ci] Upload “{{path}}”"
  deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: items
    label: Items
    folder: items
    create: true
    fields:
      - { name: name, label: Name, widget: string }
      - { name: itemId, label: ItemId, widget: string }
      - { name: image, label: Image, widget: image, required: false }